version: 2
jobs:
  go-lint:
    docker:
    - image: circleci/golang:1.12

    working_directory: /go/src/github.com/mf-financial/cayenne-wallet-util
    steps:
    - checkout
    - run: git branch -u origin/${CIRCLE_BRANCH}
    - run: go get github.com/securego/gosec/cmd/gosec/...
    - run:
        name: set environment variable
        command: |
          echo 'export GO111MODULE=on' >> $BASH_ENV
          source $BASH_ENV
    - run:
        name: go get
        command: |
          go get -u -d -v ./...
          go mod tidy
          go mod verify
          go get -u github.com/client9/misspell/cmd/misspell
          go get -u github.com/gordonklaus/ineffassign
    - run:
        name: static analysises
        command: |
          go fmt `go list ./... | grep -v "/vendor/"`
          go vet `go list ./... | grep -v "/vendor/"`
          misspell `find . -name "*.go" | grep -v "/vendor/"`
          ineffassign .
          gosec ./...
    - run:
        name: go bitcoin api test
        command: |
          go test -v ./...
workflows:
  version: 2
  build:
    jobs:
    - go-lint:
        filters:
          branches:
            only: /.*/